apiVersion: apps/v1
kind: Deployment
metadata:
  name: menuitemlisting
  labels:
    app: menuitemlisting
spec:
  replicas: 1
  selector:
    matchLabels:
      app: menuitemlisting  
  template:
    metadata:
      labels:
        app: menuitemlisting
    spec:
      containers:
      - name: menuitemlisting
        image: cloud236registry.azurecr.io/cloud236repo:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: myacrcredentailss
---
apiVersion: v1
kind: Service
metadata:
  name: menuitemlistingsvc
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: menuitemlisting