apiVersion: apps/v1
kind: Deployment
metadata:
  name: mvcapp-deployment
  labels:
    app: mvcapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mvcapp	  
  template:
    metadata:
      labels:
        app: mvcapp
    spec:
      containers:
      - name: mvcapp
        image: localhost:9000/mvcdockerdemo:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80