apiVersion: apps/v1
kind: Deployment
metadata:
  name: menuitemlisting
  labels:
    app: menuitemlisting
spec:
  replicas: 2
  selector:
    matchLabels:
      app: menuitemlisting
  template:
    metadata:
      labels:
        app: menuitemlisting
    spec:
      containers:
      - name: menuitemlisting
        image: cloudregistry236.azurecr.io/cloudpracticerepo:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        imagePullSecrets:
      - name: myacrcredentails

---
apiVersion: v1
kind: Service
metadata:
  name: menuitemlistingsvc
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: menuitemlisting